//
//  MemoDetailInteractor.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/08.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol MemoDetailBusinessLogic {
    //func setMemoDatabase()
    func requestUpdateMemoData(request: MemoDetail.저장.Request)
    func requestSaveMemoData(request: MemoDetail.저장.Request)
}

protocol MemoDetailDataStore {
}

class MemoDetailInteractor: MemoDetailBusinessLogic, MemoDetailDataStore {
    var presenter: MemoDetailPresentationLogic?
    var worker: MemoDetailWorker?
        
    // MARK: Do something
    
//    func setMemoDatabase() {
//        guard let uid = Auth.auth().currentUser?.uid else {
//            return
//        }
//
//        let ref = Database.database().reference().child("user-memo")
//        ref.setValue(uid)
//    }
    
    func requestUpdateMemoData(request: MemoDetail.저장.Request) {
        
    }
    
    func requestSaveMemoData(request: MemoDetail.저장.Request) {
        guard let memoData = request.memoData else {
            return
        }
        
        guard let uid = Auth.auth().currentUser?.uid else {
            return
        }
        
        let ref = Database.database().reference().child("user-memo")
        let childRef = ref.child(uid) //childByAutoId() -> 나중에 이거 키값으로 메모 찾아오게 autoId 메서드 미사용으로 변경
        
        // child properties
        let title = memoData.title
        let content = memoData.content
        let isFixed = memoData.isFixed
        let updatedDate = Int(Date().timeIntervalSince1970)
        let memoId:String = uid + "&" + String(updatedDate)
        let values: [String: Any] = ["uid": uid, "memoId": memoId, "title": title, "content": content, "updatedDate": updatedDate, "isFixed": isFixed]
        
        childRef.updateChildValues(values) {(error, ref) in
            if error != nil {
                print("메모저장 실패:", error!)
                self.presenter?.presentSaveFail()
                return
            }
            
            guard let memoId = childRef.key else { return }
            print("메모저장 성공: \(memoId)")
            self.presenter?.presentSaveSuccess()
            
        }
//        let ref = Database.database().reference().child("user-memo").child(uid)
//        ref.observe(.childAdded, with: { (snapshot) in
//
//        })
    }
    
//    func doSomething(request: MemoDetail.저장.Request) {
//        worker = MemoDetailWorker()
//        worker?.doSomeWork()
//
//        let response = MemoDetail.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
}
