//
//  MemoDetailPresenter.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/08.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MemoDetailPresentationLogic {
    func presentFetchData(response: MemoDetail.데이터_패치.Response)
    func presentSave(response: MemoDetail.저장.Response)
}

class MemoDetailPresenter: MemoDetailPresentationLogic {
    weak var viewController: MemoDetailDisplayLogic?
    
    // MARK: Do something

    func presentFetchData(response: MemoDetail.데이터_패치.Response) {
        viewController?.displayFetchData(viewModel: MemoDetail.데이터_패치.ViewModel(isNewMemo: response.isNewMemo, memoData: response.memoData))
    }
    
    func presentSave(response: MemoDetail.저장.Response) {
        viewController?.displaySaveData(viewModel: MemoDetail.저장.ViewModel(isSaveSuccess: response.isSaveSuccess))
    }
}
