//
//  MemoDetailRouter.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/08.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MemoDetailRoutingLogic {
    func routeToListPage()
}

protocol MemoDetailDataPassing {
    var dataStore: MemoDetailDataStore? { get }
}

class MemoDetailRouter: NSObject, MemoDetailRoutingLogic, MemoDetailDataPassing {
    weak var viewController: MemoDetailViewController?
    var dataStore: MemoDetailDataStore?
    
    // MARK: Routing
    
    func routeToListPage() {
        print("List 페이지로 돌아가기")
        viewController?.navigationController?.popViewController(animated: true)
    }
}
