//
//  MemoDetailModels.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/08.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MemoDetail {
    struct WrittenMemoData {
        var title: String?
        var content: String?
        var isFixed: Bool
    }
    
    // MARK: Use cases
    enum 데이터_패치 {
        struct Request {
        }
        struct Response {
            var isNewMemo: Bool
            var memoData: MemoData?
        }
        struct ViewModel {
            var isNewMemo: Bool
            var memoData: MemoData?
        }
    }
    
    enum 저장 {
        struct Request {
            var memoData: WrittenMemoData?
        }
        struct Response {
            var isSaveSuccess: Bool
        }
        struct ViewModel {
            var isSaveSuccess: Bool
        }
    }
}
