//
//  MainPresenter.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/22.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentAutoSignIn(response: Main.앱진입.Response)
    func presentSignIn(response: Main.로그인.Response)
    func presentSignOut(response: Main.로그아웃.Response)
    func presentRegister(response: Main.회원가입.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    func presentAutoSignIn(response: Main.앱진입.Response) {
        let viewModel = Main.앱진입.ViewModel.init(autoSign: Main.SignInStatus.init(status: response.autoSign.status, currentUserId: response.autoSign.currentUserId))
        viewController?.displayAutoSignIn(viewModel: viewModel)
    }
    
    func presentSignIn(response: Main.로그인.Response) {
        let viewModel = Main.로그인.ViewModel(signIn: response.signIn)
        viewController?.displaySignIn(viewModel: viewModel)
    }
    
    func presentSignOut(response: Main.로그아웃.Response) {
        let viewModel = Main.로그아웃.ViewModel(signOut: response.signOut)
        viewController?.displaySignOut(viewModel: viewModel)
    }
    
    func presentRegister(response: Main.회원가입.Response) {
        let viewModel = Main.회원가입.ViewModel(isRegisterSuccess: response.isRegisterSuccess, signIn: response.signIn)
        viewController?.displayRegister(viewModel: viewModel)
    }
}
