//
//  MainRouter.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/22.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToMemoListPage()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    // MARK: Routing
    func routeToMemoListPage() {
        print("Memo List 페이지로 이동")
        let destinationVC = MemoListPage()
        var destinationDS = destinationVC.router!.dataStore!
        passUserDataToList(source: dataStore!, destination: &destinationDS)
        navigateToList(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    func navigateToList(source: MainPage, destination: MemoListPage) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    func passUserDataToList(source: MainDataStore, destination: inout MemoListDataStore) {
        destination.uid = source.uid
    }
}
