//
//  MemoListRouter.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/08.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MemoListRoutingLogic {
    func routeToMemoDetailPage()
    //MARK: 매개변수(_ memoData: MemoData?)
    // -> [에러] @objc protocol protocol + method cannot be a memober
    //func routeToMemoDetailPage(_ memoData: Any?) //func routeToMemoDetailPage(_ memoData: NSObject?)
    // -> [참고] @objc protocol: https://zeddios.tistory.com/347
}

protocol MemoListDataPassing {
    var dataStore: MemoListDataStore? { get }
}

class MemoListRouter: NSObject, MemoListRoutingLogic, MemoListDataPassing {
    weak var viewController: MemoListViewController?
    var dataStore: MemoListDataStore?
    
    // MARK: Routing
    func routeToMemoDetailPage() {
        print("Memo Detail 페이지로 이동")
        
        let destinationVC = MemoDetailPage()
        var destinationDS = destinationVC.router!.dataStore!
        passMemoDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    func navigateToDetail(source: MemoListPage, destination: MemoDetailPage) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    func passMemoDataToDetail(source: MemoListDataStore, destination: inout MemoDetailDataStore) {
        guard let key = viewController?.selecteMemoKey else { //MARK: 데이터 넘기는 다른 방법 찾기
            return
        }
        
        let memoData = source.memoDataList?.filter({$0.key == key}).first        
        destination.memoData = memoData
        destination.uid = source.uid
    }
}
