//
//  MemoListModels.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/08.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MemoList {
    // MARK: Use cases
    enum MemoDataStatus {
        case 고정
        case 비고정
    }
    
    enum 조회 {
        struct Request {
        }
        struct Response {
            var memoArray: [MemoData]?
        }
        struct ViewModel {
            var memoArray: [MemoData]?
        }
    }
    
    enum 삭제 {
        struct Request {
            var key: String?
        }
        struct Response {
            var isDeleteSuccess: Bool
        }
        struct ViewModel {
            var isDeleteSuccess: Bool
        }
    }
    
    enum 고정상태_수정 {
        struct Request {
            var key: String?
            var isFixed: Bool
        }
        struct Response {
            var isChangeSuccess: Bool
            var toStatus: MemoDataStatus
        }
        struct ViewModel {
            var isChangeSuccess: Bool
            var toStatus: MemoDataStatus
        }
    }
}
