//
//  MemoListPresenter.swift
//  MemoCloneApp
//
//  Created by MUN JEONG SEO on 2021/02/08.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MemoListPresentationLogic {
    func presentMemoList(response: MemoList.조회.Response)
    func presentDelete(response: MemoList.삭제.Response)
    func presentChangeFixStatus(response: MemoList.고정상태_수정.Response)
}

class MemoListPresenter: MemoListPresentationLogic {
    weak var viewController: MemoListDisplayLogic?
    
    // MARK: Do something
    
    func presentMemoList(response: MemoList.조회.Response) {
        viewController?.displayMemoList(viewModel: MemoList.조회.ViewModel(memoArray: response.memoArray))
    }
    
    func presentDelete(response: MemoList.삭제.Response) {
            viewController?.displayDeleteMemo(viewModel: MemoList.삭제.ViewModel(isDeleteSuccess: response.isDeleteSuccess))
    }
    
    func presentChangeFixStatus(response: MemoList.고정상태_수정.Response) {
        viewController?.displayChangeFixStatus(viewModel: MemoList.고정상태_수정.ViewModel(isChangeSuccess: response.isChangeSuccess, toStatus: response.toStatus))
    }
}
